# Generated by Django 5.2.5 on 2025-09-06 13:35

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursework',
            name='answer',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True),
        ),
    ]
