# Generated by Django 5.2.5 on 2025-09-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_coursework_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursework',
            name='answer',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
