# Generated by Django 5.2.5 on 2025-09-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_coursework_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursework',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
