# Generated by Django 5.2.5 on 2025-08-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="default_dp.jpg", upload_to="profile_pics"),
        ),
    ]
