# Generated by Django 5.2.5 on 2025-08-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="theme/static/images/default_dp.jpg", upload_to="profile_pics"
            ),
        ),
    ]
