# Generated by Django 5.2.5 on 2025-10-06 12:37

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_coursework_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursework',
            name='answer',
            field=django_ckeditor_5.fields.CKEditor5Field(default=''),
            preserve_default=False,
        ),
    ]
